// AUTO-GENERATED by scripts/generate-cat-ascii.mjs — do not edit by hand.
// Source: logos/nonoise-cat.png
// Regenerate: node scripts/generate-cat-ascii.mjs
//
// CAT_MONO is plain ASCII (safe when NO_COLOR / non-TTY).
// CAT_COLOR embeds ANSI 256-color escapes approximating the logo's hues.
// Width: 14 chars, Height: 6 rows.

export const CAT_MONO: readonly string[] = [
  "   ###**###   ",
  " *#++====++#* ",
  "%#*========**%",
  " *-======-=-* ",
  " *+-======-=* ",
  " ==*++==++*== ",
];

export const CAT_COLOR: readonly string[] = [
  "   \u001b[38;5;59m#\u001b[38;5;59m#\u001b[38;5;59m#\u001b[38;5;60m*\u001b[38;5;60m*\u001b[38;5;59m#\u001b[38;5;59m#\u001b[38;5;59m#   \u001b[0m",
  " \u001b[38;5;60m*\u001b[38;5;59m#\u001b[38;5;137m+\u001b[38;5;137m+\u001b[38;5;179m=\u001b[38;5;179m=\u001b[38;5;179m=\u001b[38;5;179m=\u001b[38;5;137m+\u001b[38;5;137m+\u001b[38;5;59m#\u001b[38;5;60m* \u001b[0m",
  "\u001b[38;5;59m%\u001b[38;5;59m#\u001b[38;5;101m*\u001b[38;5;173m=\u001b[38;5;179m=\u001b[38;5;173m=\u001b[38;5;173m=\u001b[38;5;173m=\u001b[38;5;173m=\u001b[38;5;179m=\u001b[38;5;173m=\u001b[38;5;101m*\u001b[38;5;65m*\u001b[38;5;59m%\u001b[0m",
  " \u001b[38;5;101m*\u001b[38;5;215m-\u001b[38;5;179m=\u001b[38;5;179m=\u001b[38;5;179m=\u001b[38;5;179m=\u001b[38;5;179m=\u001b[38;5;179m=\u001b[38;5;179m-\u001b[38;5;179m=\u001b[38;5;215m-\u001b[38;5;95m* \u001b[0m",
  " \u001b[38;5;94m*\u001b[38;5;173m+\u001b[38;5;215m-\u001b[38;5;215m=\u001b[38;5;172m=\u001b[38;5;172m=\u001b[38;5;172m=\u001b[38;5;172m=\u001b[38;5;215m=\u001b[38;5;215m-\u001b[38;5;173m=\u001b[38;5;94m* \u001b[0m",
  " \u001b[38;5;179m=\u001b[38;5;173m=\u001b[38;5;130m*\u001b[38;5;172m+\u001b[38;5;172m+\u001b[38;5;172m=\u001b[38;5;172m=\u001b[38;5;172m+\u001b[38;5;172m+\u001b[38;5;136m*\u001b[38;5;173m=\u001b[38;5;179m= \u001b[0m",
];

export const CAT_WIDTH = 14;
export const CAT_HEIGHT = 6;
